version: "3"
services:
  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission
    restart: always
    environment:
      # Set user id(libvirt-qemu)
      - PUID=${USER_ID}
      - TZ
      - TRANSMISSION_WEB_HOME=/combustion-release/
    ports:
      # do you actually need this for proper functionality?
      - ${WEB_PORT}:9091
      - ${API_PORT}:51413
      - ${API_PORT}:51413/udp
    volumes:
      - .config:/config
      - /srv/transmission/downloads:/downloads
      - /srv/transmission/watch:/watch

#networks:
#  default:
#    external:
#      name: caddynet
